name: get-data

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  get-data:
    name: Get Data
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - uses: bahmutov/npm-install@v1
      - name: Get Data
        env:
          MMR_AUTH_TOKEN: ${{ secrets.MMR_AUTH_TOKEN }}
          MMR_USER_ID: ${{ secrets.MMR_USER_ID }}
          SANITY_PROJECT_ID: ${{ secrets.SANITY_PROJECT_ID }}
          SANITY_API_TOKEN_WRITE: ${{ secrets.SANITY_API_TOKEN_WRITE }}
        run: npm run get-data
