# This is a basic workflow that is manually triggered

name: Get Data

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    
      

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

  getdata:
    name: Get Data
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Get The Data
        run: npm run get-data
